
import React, { useState, useEffect } from 'react';
import { User } from '../types';
import Logo from './Logo';

interface AdminPageProps {
  onBack: () => void;
  onNavigateToLoginHistory: () => void;
  loginHistoryCount: number;
  authorizedUsers: User[];
  onUpdateUsers: (users: User[]) => void;
}

const AdminPage: React.FC<AdminPageProps> = ({ onBack, onNavigateToLoginHistory, loginHistoryCount, authorizedUsers, onUpdateUsers }) => {
    const [users, setUsers] = useState<User[]>(authorizedUsers);
    const [newUserEmail, setNewUserEmail] = useState('');
    const [emailError, setEmailError] = useState('');

    useEffect(() => {
        setUsers(authorizedUsers);
    }, [authorizedUsers]);

    const handleAddUser = () => {
        const email = newUserEmail.trim().toLowerCase();
        if (!email) {
            setEmailError('Email cannot be empty.');
            return;
        }
        if (!/\S+@\S+\.\S+/.test(email)) {
             setEmailError('Please enter a valid email address.');
            return;
        }
        if (users.some(u => u.email === email)) {
            setEmailError('This user already exists.');
            return;
        }
        // A real UID will be generated by Firebase Auth, but we need a placeholder for the optimistic update.
        const placeholderUid = `temp-${Date.now()}`; 
        const updatedUsers: User[] = [...users, { email, role: 'user', uid: placeholderUid }];
        setUsers(updatedUsers);
        onUpdateUsers(updatedUsers);
        setNewUserEmail('');
        setEmailError('');
    };
    
    const handleDeleteUser = (emailToDelete: string) => {
        if (window.confirm(`Are you sure you want to remove ${emailToDelete}? This action cannot be undone.`)) {
            const updatedUsers = users.filter(u => u.email !== emailToDelete);
            setUsers(updatedUsers);
            onUpdateUsers(updatedUsers);
        }
    };

    return (
        <div className="max-w-5xl mx-auto">
            <button onClick={onBack} className="absolute top-6 right-6 text-slate-400 hover:text-white transition-colors z-10" aria-label="Back to Home">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z" /></svg>
            </button>
            <header className="bg-indigo-950 text-white p-6 text-center rounded-lg shadow-lg mb-8 relative">
                <h1 className="text-3xl sm:text-4xl font-bold flex items-center justify-center gap-3">
                    <Logo className="w-10 h-10" />
                    <span>פאנל ניהול</span>
                </h1>
                <h2 className="text-lg sm:text-xl font-light mt-1 text-slate-300">ניהול משתמשים ומעקב מערכת</h2>
            </header>
            <div className="bg-slate-800 rounded-lg shadow-md p-6 sm:p-8 space-y-10">

                {/* Login History Section */}
                <div className="bg-slate-900/50 p-6 rounded-lg">
                    <h3 className="text-2xl font-bold text-orange-400 mb-4">מעקב התחברויות</h3>
                    <p className="text-slate-300 mb-4">
                        סה"כ <span className="font-bold text-white">{loginHistoryCount}</span> התחברויות נרשמו במערכת.
                    </p>
                    <button 
                        onClick={onNavigateToLoginHistory}
                        className="bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 px-5 rounded-lg shadow-md transition-colors"
                    >
                        צפה בהיסטוריית ההתחברויות המלאה
                    </button>
                </div>

                {/* User Management Section */}
                <div className="bg-slate-900/50 p-6 rounded-lg">
                    <h3 className="text-2xl font-bold text-orange-400 mb-4">ניהול משתמשים מורשים</h3>
                    <div className="mb-6 space-y-3">
                        {users.map(user => (
                            <div key={user.uid} className="flex justify-between items-center bg-slate-800 p-3 rounded-md">
                                <div>
                                    <p className="text-white font-mono">{user.email}</p>
                                    <p className={`text-sm font-bold ${user.role === 'admin' ? 'text-green-400' : 'text-slate-400'}`}>{user.role.toUpperCase()}</p>
                                </div>
                                {user.role !== 'admin' && (
                                    <button 
                                        onClick={() => handleDeleteUser(user.email)}
                                        className="bg-red-600 hover:bg-red-700 text-white font-bold py-1 px-3 rounded text-sm"
                                    >
                                        מחק
                                    </button>
                                )}
                            </div>
                        ))}
                    </div>
                     <div className="border-t border-slate-700 pt-4">
                        <h4 className="text-lg font-semibold text-slate-200 mb-2">הוספת משתמש חדש</h4>
                        <p className="text-sm text-slate-400 mb-3">
                            המשתמש יתווסף עם הרשאת 'user' רגילה. כדי להפוך משתמש לאדמין, עליך לערוך את הרשאתו ישירות במסד הנתונים של Firestore.
                        </p>
                        <div className="flex flex-col sm:flex-row gap-2">
                            <input
                                type="email"
                                value={newUserEmail}
                                onChange={(e) => { setNewUserEmail(e.target.value); setEmailError(''); }}
                                placeholder="הכנס כתובת מייל חדשה"
                                className="flex-grow bg-slate-700 text-white p-3 rounded-md border-2 border-slate-600 focus:border-orange-500 focus:outline-none transition-colors"
                                dir="ltr"
                            />
                            <button 
                                onClick={handleAddUser}
                                className="bg-green-600 hover:bg-green-700 text-white font-bold py-3 px-5 rounded-md"
                            >
                                הוסף משתמש
                            </button>
                        </div>
                     </div>
                     {emailError && <p className="text-red-400 text-sm mt-2">{emailError}</p>}
                </div>

                 <div className="bg-slate-900/50 p-6 rounded-lg">
                    <h3 className="text-2xl font-bold text-orange-400 mb-2">איך זה עובד?</h3>
                    <p className="text-slate-300 mb-4">
                        רשימת המשתמשים נשמרת כעת במסד נתונים (Firestore) מרכזי. כל שינוי שתבצע כאן יתעדכן שם באופן מיידי. משתמש חדש שתנסה להוסיף יתווסף למערכת, אך יוכל להתחבר רק לאחר שישלים הרשמה ראשונית באמצעות חשבון הגוגל שלו.
                    </p>
                     <p className="text-yellow-400 bg-yellow-900/50 border border-yellow-700 p-3 mt-4 rounded-md text-sm">
                        <strong>אין צורך יותר בעדכון קבצי קוד ופרסום מחדש!</strong> הניהול מתבצע בזמן אמת.
                    </p>
                </div>
            </div>
        </div>
    );
};

export default AdminPage;
